fn main() {
  // ERROR:
  let x = foo(bar(1 + 42))
}