func foo() {
    // ERROR:
    foo(bar(1 + 42))
}
