def foo()
  #ERROR: match
  return 1 & 3
end
