z = 3


def foo():
    # ERROR:
    pass
