def foo() do
  #ERROR:
    myfile = open()
    close(myfile)
end




