Fixed a bug in the generation of the control-flow graph for `try` statements that
could e.g. cause taint to report false positives:

    def test():
        data = taint
        try:
            # Semgrep assumes that `clean` could raise an exception, but
            # even if it does, the tainted `data` will never reach the sink !
            data = clean(data)
        except Exception:
            raise Exception()

        # `data` must be clean here
        sink(data) # no more FP
