
val x = 
  try 2
  catch case _ => 4